codigo_banco: 0..2
lote_servico: 3..6
tipo_registro: 7..7
filler_a: 8..16
tipo_inscr_empresa: 17..17
num_inscr_empresa: 18..31
cod_convenio_banco: 32..51
ag_mantenedora_sonta: 52..56
dig_verif_agencia: 57..57
num_conta_corrente: 58..69
dig_verif_conta: 70..70
dig_verif_ag_conta: 71..71
nome_empresa: 72..101
nome_banco: 102..131
filler_b: 132..141
cod_remessa_retorno: 142..142
data_geracao_arq: 143..150
hora_geracao_arq: 151..156
num_sequencial_arq: 157..162
num_versao_layout: 163..165
dens_grav_arq: 166..170
uso_reservado_banco: 171..190
uso_reservado_empresa: 191..210
filler_c: 211..229
ocorrencias_retorno: 230..239
