banco: 0..2
lote: 3..6
tipo_registro: 7..7
num_registro: 8..12
segmento: 13..13
res_banco1: 14..14
cod_movimentacao: 15..16
tipo_inscricao_sacador: 17..17
num_inscricao_sacador: 18..32
nome_sacador: 33..72
cod_desconto_2: 73..73
data_desconto_2: 74..81
valor_percentual_desconto_2: 82..96
cod_desconto_3: 97..97
data_desconto_3: 98..105
valor_percentual_desconto_3: 106..120
cod_multa: 121..121
data_multa: 122..129
valor_multa: 130..144
valor_abatimento: 145..159
mensagem_1: 160..199
mensagem_2: 200..239
